export const APP_ROUTE = {
  DASHBOARD: '/dashboard',
  CATEGORY: '/categories',
  TOPIC: '/topic',
  BLOG: '/blogs',
  CREATE_BLOG: '/blogs/create',
  SIGN_IN: '/auth/sign-in',
  SIGN_UP: '/auth/sign-up',
  FORGOT: '/auth/forgot-password',
  VERIFY: '/auth/verify-email',
  STORES: '/stores',
  ADD_STORE: '/stores/create',
  COUPONS: '/coupons',
  ADD_COUPON: '/coupons/create',
  SUBMIT_COUPON: '/coupons/submit',
  SIGN_OUT: '/auth/sign-out',
};
